name: task

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '1 0,5,12 * * *'


jobs:
  task:
    name: im fine
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run_1
        run: |
          python ./main.py ${{ secrets.USER }} ${{ secrets.PASS }}
      - name: Run_2
        run: |
          python ./main.py ${{ secrets.USER2 }} ${{ secrets.PASS2 }}
